server:
  port: 8770

spring:
  application:
    name: chainmonitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false